# Generated by Django 4.0.6 on 2022-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_auto_20221006_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='test', max_length=300),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
